using System.Globalization;

namespace CodexUsageTray;

public enum TextId
{
    AlreadyRunning,
    ConnectionToCodex,
    SyncingWithCodex,
    QuotasSynced,
    QuotasSyncedHistoryUnavailable,
    RefreshFailed,
    SyncError,
    CodexUnavailable,
    CodexNotLoggedIn,
    QuotasUnavailable,
    Open,
    Refresh,
    Settings,
    Exit,
    Language,
    English,
    French,
    DetachWidget,
    BackToFullView,
    Hide,
    Activity,
    Today,
    Total,
    Streak,
    ActivityUnit,
    Tokens,
    ResetAvailable,
    ResetProvidedByOpenAi,
    ResetInformationUnavailable,
    NoResetCredits,
    OneResetCredit,
    ManyResetCredits,
    NeverRefreshed,
    SyncedAt,
    PendingSync,
    CodexQuota,
    Remaining,
    MainQuota,
    ModelQuota,
    CurrentWindow,
    UnknownDeadline,
    ResetsAt,
    PercentRemaining,
    PercentUsed,
    EstimateUnavailable,
    EstimateDetails,
    ProxyPricing,
    UnknownModels,
    EstimateTooltip,
    ModelBreakdown,
    ModelBreakdownSubtitle,
    Model,
    Models,
    Effort,
    Sessions,
    ApiCost,
    TokenShare,
    InputTokens,
    CachedTokens,
    OutputTokens,
    ObservedTokens,
    SearchModels,
    Options,
    SettingsSubtitle,
    General,
    RefreshInterval,
    StartupBehavior,
    FullWindow,
    CompactWidget,
    TrayOnly,
    LastUsedView,
    UiScale,
    CompactAlwaysOnTop,
    DockPosition,
    TopLeft,
    TopRight,
    BottomLeft,
    BottomRight,
    StartWithWindows,
    ResetSettings,
    ApiEquivalent,
    ApiEquivalentDescription,
    ClearLocalCache,
    ClearCacheDescription,
    ClearCacheConfirmation,
    ClearCacheTitle,
    CacheCleared,
    UpdateAvailableTitle,
    UpdateAvailableMessage,
    UpdateProgressTitle,
    UpdateDownloading,
    UpdateVerifying,
    UpdatePreparing,
    UpdateFailedTitle,
    UpdateFailedMessage,
    Cancel,
    OneMinute,
    FiveMinutes,
    FifteenMinutes
}

public static class AppText
{
    private static readonly IReadOnlyDictionary<TextId, string> English = new Dictionary<TextId, string>
    {
        [TextId.AlreadyRunning] = "Codex Meter is already running.",
        [TextId.ConnectionToCodex] = "Connecting to Codex…",
        [TextId.SyncingWithCodex] = "Syncing with Codex…",
        [TextId.QuotasSynced] = "Connected · quotas synced",
        [TextId.QuotasSyncedHistoryUnavailable] = "Quotas synced · local history unavailable.",
        [TextId.RefreshFailed] = "Refresh failed",
        [TextId.SyncError] = "Sync error",
        [TextId.CodexUnavailable] = "Codex was not found. Install Codex or set CODEX_USAGE_TRAY_CODEX_PATH.",
        [TextId.CodexNotLoggedIn] = "Codex is not signed in. Run ‘codex login’, then refresh.",
        [TextId.QuotasUnavailable] = "Could not read quotas. Refresh and make sure Codex is running.",
        [TextId.Open] = "Open",
        [TextId.Refresh] = "Refresh",
        [TextId.Settings] = "Settings",
        [TextId.Exit] = "Exit",
        [TextId.Language] = "Language",
        [TextId.English] = "English",
        [TextId.French] = "Français",
        [TextId.DetachWidget] = "Detach as widget",
        [TextId.BackToFullView] = "Back to full view",
        [TextId.Hide] = "Hide",
        [TextId.Activity] = "ACTIVITY",
        [TextId.Today] = "TODAY",
        [TextId.Total] = "TOTAL",
        [TextId.Streak] = "STREAK",
        [TextId.ActivityUnit] = "activity",
        [TextId.Tokens] = "tokens",
        [TextId.ResetAvailable] = "OpenAI reset available",
        [TextId.ResetProvidedByOpenAi] = "Credit provided by OpenAI",
        [TextId.ResetInformationUnavailable] = "Information unavailable",
        [TextId.NoResetCredits] = "No credit available",
        [TextId.OneResetCredit] = "1 credit ready to use in Codex",
        [TextId.ManyResetCredits] = "{0} credits ready to use in Codex",
        [TextId.NeverRefreshed] = "Not refreshed yet",
        [TextId.SyncedAt] = "Synced at {0}",
        [TextId.PendingSync] = "Waiting for sync",
        [TextId.CodexQuota] = "CODEX QUOTA",
        [TextId.Remaining] = "remaining",
        [TextId.MainQuota] = "MAIN QUOTA",
        [TextId.ModelQuota] = "MODEL QUOTA",
        [TextId.CurrentWindow] = "Current window",
        [TextId.UnknownDeadline] = "Unknown reset",
        [TextId.ResetsAt] = "Resets {0}",
        [TextId.PercentRemaining] = "% remaining",
        [TextId.PercentUsed] = "{0}% used",
        [TextId.EstimateUnavailable] = "Estimate unavailable: no usable local counters.",
        [TextId.EstimateDetails] = "Local estimate from {0:N0} sessions using current public API prices.",
        [TextId.ProxyPricing] = " Spark uses GPT-5.3-Codex pricing because its final public price is not available.",
        [TextId.UnknownModels] = " Models without public prices were skipped: {0}.",
        [TextId.EstimateTooltip] = "Estimated using current public API prices. Local calculation only.",
        [TextId.ModelBreakdown] = "Model details",
        [TextId.ModelBreakdownSubtitle] = "Observed local sessions · API-equivalent cost",
        [TextId.Model] = "MODEL",
        [TextId.Models] = "MODELS",
        [TextId.Effort] = "EFFORT",
        [TextId.Sessions] = "SESSIONS",
        [TextId.ApiCost] = "API COST",
        [TextId.TokenShare] = "SHARE",
        [TextId.InputTokens] = "Input",
        [TextId.CachedTokens] = "cached",
        [TextId.OutputTokens] = "output",
        [TextId.ObservedTokens] = "OBSERVED TOKENS",
        [TextId.SearchModels] = "Search models…",
        [TextId.Options] = "Options",
        [TextId.SettingsSubtitle] = "Tune Codex Meter to your desk.",
        [TextId.General] = "GENERAL",
        [TextId.RefreshInterval] = "Refresh interval",
        [TextId.StartupBehavior] = "At startup",
        [TextId.FullWindow] = "Full window",
        [TextId.CompactWidget] = "Compact widget",
        [TextId.TrayOnly] = "Tray only",
        [TextId.LastUsedView] = "Last used view",
        [TextId.UiScale] = "UI scale",
        [TextId.CompactAlwaysOnTop] = "Keep compact widget on top",
        [TextId.DockPosition] = "Compact dock position",
        [TextId.TopLeft] = "Top left",
        [TextId.TopRight] = "Top right",
        [TextId.BottomLeft] = "Bottom left",
        [TextId.BottomRight] = "Bottom right",
        [TextId.StartWithWindows] = "Start with Windows",
        [TextId.ResetSettings] = "Reset settings",
        [TextId.ApiEquivalent] = "API-equivalent estimate",
        [TextId.ApiEquivalentDescription] = "Reads local session counters only. No prompts, keys, or telemetry.",
        [TextId.ClearLocalCache] = "Clear local estimate cache",
        [TextId.ClearCacheDescription] = "Removes Codex Meter’s local estimate cache only.",
        [TextId.ClearCacheConfirmation] = "Clear Codex Meter’s local estimate cache? This does not affect Codex or its sessions.",
        [TextId.ClearCacheTitle] = "Clear local cache",
        [TextId.CacheCleared] = "Local estimate cache cleared.",
        [TextId.UpdateAvailableTitle] = "Update available",
        [TextId.UpdateAvailableMessage] = "Codex Meter {0} is available. Download it now and restart automatically?",
        [TextId.UpdateProgressTitle] = "Updating Codex Meter to {0}",
        [TextId.UpdateDownloading] = "Downloading the update…",
        [TextId.UpdateVerifying] = "Verifying the secure download…",
        [TextId.UpdatePreparing] = "Preparing the restart…",
        [TextId.UpdateFailedTitle] = "Update failed",
        [TextId.UpdateFailedMessage] = "The update could not be installed. Codex Meter was not changed.",
        [TextId.Cancel] = "Cancel",
        [TextId.OneMinute] = "1 minute",
        [TextId.FiveMinutes] = "5 minutes",
        [TextId.FifteenMinutes] = "15 minutes"
    };

    private static readonly IReadOnlyDictionary<TextId, string> French = new Dictionary<TextId, string>
    {
        [TextId.AlreadyRunning] = "Codex Meter est déjà lancé.",
        [TextId.ConnectionToCodex] = "Connexion à Codex…",
        [TextId.SyncingWithCodex] = "Synchronisation avec Codex…",
        [TextId.QuotasSynced] = "Connecté · quotas synchronisés",
        [TextId.QuotasSyncedHistoryUnavailable] = "Quotas synchronisés · historique local indisponible.",
        [TextId.RefreshFailed] = "Échec de l’actualisation",
        [TextId.SyncError] = "Erreur de synchronisation",
        [TextId.CodexUnavailable] = "Codex est introuvable. Installez Codex ou définissez CODEX_USAGE_TRAY_CODEX_PATH.",
        [TextId.CodexNotLoggedIn] = "Codex n’est pas connecté. Lancez « codex login », puis actualisez.",
        [TextId.QuotasUnavailable] = "Impossible de lire les quotas. Actualisez et vérifiez que Codex est lancé.",
        [TextId.Open] = "Ouvrir",
        [TextId.Refresh] = "Actualiser",
        [TextId.Settings] = "Paramètres",
        [TextId.Exit] = "Quitter",
        [TextId.Language] = "Langue",
        [TextId.English] = "English",
        [TextId.French] = "Français",
        [TextId.DetachWidget] = "Détacher en widget",
        [TextId.BackToFullView] = "Revenir à la vue complète",
        [TextId.Hide] = "Masquer",
        [TextId.Activity] = "ACTIVITÉ",
        [TextId.Today] = "AUJOURD’HUI",
        [TextId.Total] = "TOTAL",
        [TextId.Streak] = "SÉRIE",
        [TextId.ActivityUnit] = "activité",
        [TextId.Tokens] = "tokens",
        [TextId.ResetAvailable] = "Reset OpenAI disponible",
        [TextId.ResetProvidedByOpenAi] = "Crédit fourni par OpenAI",
        [TextId.ResetInformationUnavailable] = "Information non fournie",
        [TextId.NoResetCredits] = "Aucun crédit disponible",
        [TextId.OneResetCredit] = "1 crédit prêt à être utilisé dans Codex",
        [TextId.ManyResetCredits] = "{0} crédits prêts à être utilisés dans Codex",
        [TextId.NeverRefreshed] = "Pas encore actualisé",
        [TextId.SyncedAt] = "Synchronisé à {0}",
        [TextId.PendingSync] = "En attente de synchronisation",
        [TextId.CodexQuota] = "QUOTA CODEX",
        [TextId.Remaining] = "restant",
        [TextId.MainQuota] = "QUOTA PRINCIPAL",
        [TextId.ModelQuota] = "QUOTA MODÈLE",
        [TextId.CurrentWindow] = "Fenêtre courante",
        [TextId.UnknownDeadline] = "Échéance inconnue",
        [TextId.ResetsAt] = "Reset {0}",
        [TextId.PercentRemaining] = "% restant",
        [TextId.PercentUsed] = "{0}% consommé",
        [TextId.EstimateUnavailable] = "Estimation indisponible : aucun compteur local exploitable.",
        [TextId.EstimateDetails] = "Estimation locale sur {0:N0} sessions, selon les tarifs API publics actuels.",
        [TextId.ProxyPricing] = " Spark est valorisé au tarif GPT-5.3-Codex, son tarif final n’étant pas public.",
        [TextId.UnknownModels] = " Modèles sans tarif public ignorés : {0}.",
        [TextId.EstimateTooltip] = "Équivalent estimé aux tarifs API publics actuels. Calcul local.",
        [TextId.ModelBreakdown] = "Détail par modèle",
        [TextId.ModelBreakdownSubtitle] = "Sessions locales observées · coût équivalent API",
        [TextId.Model] = "MODÈLE",
        [TextId.Models] = "MODÈLES",
        [TextId.Effort] = "EFFORT",
        [TextId.Sessions] = "SESSIONS",
        [TextId.ApiCost] = "COÛT API",
        [TextId.TokenShare] = "PART",
        [TextId.InputTokens] = "Entrée",
        [TextId.CachedTokens] = "cache",
        [TextId.OutputTokens] = "sortie",
        [TextId.ObservedTokens] = "TOKENS OBSERVÉS",
        [TextId.SearchModels] = "Rechercher un modèle…",
        [TextId.Options] = "Options",
        [TextId.SettingsSubtitle] = "Adaptez Codex Meter \u00e0 votre bureau.",
        [TextId.General] = "GÉNÉRAL",
        [TextId.RefreshInterval] = "Intervalle d’actualisation",
        [TextId.StartupBehavior] = "Au démarrage",
        [TextId.FullWindow] = "Fenêtre complète",
        [TextId.CompactWidget] = "Widget compact",
        [TextId.TrayOnly] = "Tray uniquement",
        [TextId.LastUsedView] = "Dernière vue utilisée",
        [TextId.UiScale] = "Échelle de l’interface",
        [TextId.CompactAlwaysOnTop] = "Garder le widget compact au premier plan",
        [TextId.DockPosition] = "Position dâ€™ancrage du widget",
        [TextId.TopLeft] = "En haut Ã  gauche",
        [TextId.TopRight] = "En haut Ã  droite",
        [TextId.BottomLeft] = "En bas Ã  gauche",
        [TextId.BottomRight] = "En bas Ã  droite",
        [TextId.StartWithWindows] = "DÃ©marrer avec Windows",
        [TextId.ResetSettings] = "RÃ©initialiser les rÃ©glages",
        [TextId.ApiEquivalent] = "Estimation équivalente API",
        [TextId.ApiEquivalentDescription] = "Lit uniquement les compteurs de sessions locaux. Aucun prompt, clé ou télémétrie.",
        [TextId.ClearLocalCache] = "Effacer le cache local d’estimation",
        [TextId.ClearCacheDescription] = "Supprime uniquement le cache local d’estimation de Codex Meter.",
        [TextId.ClearCacheConfirmation] = "Effacer le cache local d’estimation de Codex Meter ? Cela n’affecte ni Codex ni ses sessions.",
        [TextId.ClearCacheTitle] = "Effacer le cache local",
        [TextId.CacheCleared] = "Cache local d’estimation effacé.",
        [TextId.UpdateAvailableTitle] = "Mise à jour disponible",
        [TextId.UpdateAvailableMessage] = "Codex Meter {0} est disponible. La télécharger maintenant et redémarrer automatiquement ?",
        [TextId.UpdateProgressTitle] = "Mise à jour de Codex Meter vers {0}",
        [TextId.UpdateDownloading] = "Téléchargement de la mise à jour…",
        [TextId.UpdateVerifying] = "Vérification du téléchargement sécurisé…",
        [TextId.UpdatePreparing] = "Préparation du redémarrage…",
        [TextId.UpdateFailedTitle] = "Échec de la mise à jour",
        [TextId.UpdateFailedMessage] = "La mise à jour n’a pas pu être installée. Codex Meter n’a pas été modifié.",
        [TextId.Cancel] = "Annuler",
        [TextId.OneMinute] = "1 minute",
        [TextId.FiveMinutes] = "5 minutes",
        [TextId.FifteenMinutes] = "15 minutes"
    };

    public static CultureInfo Culture(AppLanguage language) => language == AppLanguage.French
        ? CultureInfo.GetCultureInfo("fr-FR")
        : CultureInfo.GetCultureInfo("en-US");

    public static string Get(AppLanguage language, TextId id) => (language == AppLanguage.French ? French : English)[id];

    public static string Format(AppLanguage language, TextId id, params object?[] arguments) =>
        string.Format(Culture(language), Get(language, id), arguments);
}
